name: Lint

on:
  push:
    branches:
      - main
      - develop
      - setup/eslint
  pull_request:
    branches:
      - main
      - develop
      - setup/eslint

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Fix permissions
        run: chmod +x ./node_modules/.bin/eslint

      - name: Run ESLint
        run: npx eslint 'Zuydle/src/**/*.{ts,tsx}'