name: Snyk Security

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installeer Snyk CLI om beveiligingsproblemen te controleren
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Code test uitvoeren
        run: snyk code test --sarif > snyk-code.sarif || true

      - name: Snyk Open Source monitor uitvoeren
        run: snyk monitor --all-projects --severity-threshold=high || true

      - name: Snyk IaC test uitvoeren en rapporteren
        run: snyk iac test --report || true

      - name: Bouw een Docker-image
        run: docker build -t your/image-to-test .

      - name: Snyk Container monitor uitvoeren
        run: snyk container monitor your/image-to-test --file=Dockerfile --severity-threshold=high || true

      - name: Upload resultaten naar GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
